@startuml
class Direccion{
  cp: string
  localidad: string
  > provincia: string
  > calle: string
  numero: int
}

class Envio{
  > codigo: string
  > peso: float
  precio: float
  observaciones: string
}


Direccion "1" -- "*" Envio: origen
Direccion "1" -- "*" Envio: destino
@enduml